### ISSUE TITLE
One issue with no scalable icons: volume meter

### ISSUE THREAD

**Issue by sawyer07** [lainsce/retrostep-icons#1]
The only problem I have had so far with all icons being 48px is the fact that the status/audio-volume-*.png icons are called and displayed rather large on the screen certain environments (my personal setup mystifies me at times, but I believe this is coming from MATE) – the result is that having upgraded in a sense from GNUstep icon theme to retrostep, when I adjust the volume a very blurry audio level icon is rendered.

A cursory investigation yields that the workaround for this used in the GNUstep icon theme (at least the version I have) these images are actually 144x144 pixels in size, despite being in the usual directory called "48." 

I am unaware of any other case in which the icons are not 48x48, nor any other situation where this would be necessary.

For my part I think I will just copy the higher resolution icons from GNUstep and override the smaller ones in retrostep, but I thought you might like to know as this aspect of my setup represents probably a significant user base 

Thanks – again :) – for this project!

**Comment by lainsce** [comment]
Actually, I was going to complete the 48 set in all places, then move up and down. These take a bit of time to make due to complexity.
